single_fit:
  epochs: 200000
  stop_loss: 1.e-5
  patience: 100
  optimizer: SGD
  lr: 1.e+4
  momentum: 0.5
  nesterov: True

ecsecb_tetramer_dimer:
  r1: 2
  r2: 2
  epochs: 200000
  stop_loss: 1.e-5
  patience: 100
  optimizer: SGD
  lr: 1.e+4
  momentum: 0.5
  nesterov: True

seca_all_states:
  epochs: 150000
  r1: 2
  r2: 2
  stop_loss: 1.e-5
  patience: 50
  optimizer: SGD
  lr: 1.e+5
  momentum: 0.5
  nesterov: True

ecsecb_mtsecb:
  r1: 1
  r2: 1
  epochs: 200000
  stop_loss: 5.e-6
  patience: 100
  optimizer: SGD
  lr: 1.e+4
  momentum: 0.5
  nesterov: True

