single_fit:
  epochs: 200000
  stop_loss: 0.01
  patience: 100
  optimizer: SGD
  lr: 10
  momentum: 0.5
  nesterov: True

ecsecb_tetramer_dimer:
  r1: 0.05
  r2: 0.1
  epochs: 100000
  stop_loss: 0.05
  patience: 50
  optimizer: SGD
  lr: 10
  momentum: 0.5
  nesterov: True

seca_all_states:
  epochs: 100000
  r1: 0.5
  r2: 0.5
  stop_loss: 0.05
  patience: 50
  optimizer: SGD
  lr: 10
  momentum: 0.5
  nesterov: True

ecsecb_mtsecb:
  r1: 0.05
  r2: 0.5
  epochs: 100000
  stop_loss: 0.05
  patience: 50
  optimizer: SGD
  lr: 10
  momentum: 0.5
  nesterov: True