alignment_ss = {
    'ecSecB': '------------MSEQNNTEMTFQIQRIYTKDISFEAPNaphvfqkdwqPEVKLDLDTASSQLAD--DVYEVVLRVTVTASLGEE--------------TAFLCEVQQGGIFSIAGIEGTQMA------HCLGAYCPNILFPYARECITSMVSRGTFPQLNLAPVNFDALFMNYLQQQAGEGTEEHQDA',
    'mtSecB': 'MTDRTDADDLDLQRVGARLAARAQIRDIRLLRTQAAVHRAPKPAQG---LTYDLEFEPAVDADPATISAFVVRISCHLRIQNQAADDDVKEGDTKDETQDVATADFEFAALFDYHLQEGEDDPTEEELTAYAATTGRFALYPYIREYVYDLTGRLALPPLTLEILSRPMPVSPGAQWPATRGTP-----',
}

alignment_clustal = {
    'ecSecB': 'MSEQNNT-EMT-----------FQIQ---RIYTKDISFEAP--NAPHVFQKDWQPEVKLDLDTASSQLADDVYEVVLRVTVTASL-----------GE---ET--AFLCEVQQGGIFSIAGIEGT------QMAHCLGAYCPNILFPYARECITSMVSRGTFPQLNLAPVNFDALFMNYLQQQAGEGTEEHQDA',
    'mtSecB': 'MTDRTDADDLDLQRVGARLAARAQIRDIRLLRTQAAVHRAPKPAQGLTYDLEFEPAVDADPATISA--------FVVRISCHLRIQNQAADDDVKEGDTKDETQDVATADFEFAALFDYHLQEGEDDPTEEELTAYAATTGRFALYPYIREYVYDLTGRLALPPLTLEILSRPMPVSPGAQWPATRGTP-----',
}

unaligned = {k: v.replace('-', '') for k, v in alignment_clustal.items()}

#todo this should be a dict
#alignments = [alignment_ss, alignment_clustal, no_alignment]

alignments = {
     'secondary_structure': alignment_ss,
     'clustal': alignment_clustal,
     'unaligned': unaligned
}